apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-webapp-deployment
  labels:
    app: sa-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-webapp
  template:
    metadata:
      labels:
        app: sa-webapp
    spec:
      containers:
      - name: sa-webapp
        image: yuhan509/cloudinfra-hw5-webapp:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SA_LOGIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: sa-webapp-configmap
              key: sa_logic_url