apiVersion: v1
kind: Service
metadata:
  name: sa-front-service
spec:
  selector:
    app: sa-front
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30000