apiVersion: v1
kind: Service
metadata:
  name: sa-webapp-service
spec:
  selector:
    app: sa-webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010